# Generated by Django 6.0.6 on 2026-06-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('volume_horaire_max', models.FloatField(default=20.0, help_text='Volume horaire max par semaine')),
                ('temps_partiel', models.BooleanField(default=False)),
                ('prefere_eviter_apres_16h', models.BooleanField(default=False)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='subjects.matiere')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('est_disponible', models.BooleanField(default=True, help_text='True = disponible, False = indisponible')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='teachers.enseignant')),
            ],
            options={
                'verbose_name': 'Disponibilité enseignant',
                'verbose_name_plural': 'Disponibilités enseignants',
                'ordering': ['enseignant', 'jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='EnseignantClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.enseignant')),
            ],
            options={
                'verbose_name': 'Affectation enseignant-classe',
                'verbose_name_plural': 'Affectations enseignants-classes',
                'unique_together': {('enseignant', 'classe')},
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='classes',
            field=models.ManyToManyField(related_name='enseignants', through='teachers.EnseignantClasse', to='classes.classe'),
        ),
    ]
