# Generated by Django 6.0.6 on 2026-06-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('capacite', models.IntegerField()),
                ('type', models.CharField(choices=[('NORMALE', 'Salle normale'), ('LABORATOIRE', 'Laboratoire'), ('ATELIER', 'Atelier'), ('INFORMATIQUE', 'Salle informatique')], default='NORMALE', max_length=20)),
                ('est_salle_unique', models.BooleanField(default=False, help_text="True si c'est une salle unique (ex: seule salle informatique)")),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('est_disponible', models.BooleanField(default=True, help_text='True = disponible, False = indisponible')),
                ('motif', models.CharField(blank=True, help_text="Motif d'indisponibilité (maintenance, etc.)", max_length=200)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='rooms.salle')),
            ],
            options={
                'verbose_name': 'Disponibilité salle',
                'verbose_name_plural': 'Disponibilités salles',
                'ordering': ['salle', 'jour_semaine', 'heure_debut'],
            },
        ),
    ]
