# Generated by Django 5.1.6 on 2026-08-19 07:48

import django.db.models.deletion
from django.db import migrations, models


def create_class_rooms(apps, schema_editor):
    Classe = apps.get_model('classes', 'Classe')
    Salle = apps.get_model('rooms', 'Salle')
    for cls in Classe.objects.all():
        expected = f"Salle {cls.nom}"
        if Salle.objects.filter(classe=cls).exists():
            continue
        room = Salle.objects.filter(nom=expected).first()
        if room is None:
            Salle.objects.create(
                nom=expected,
                capacite=cls.effectif,
                type='NORMALE',
                est_salle_unique=False,
                classe=cls,
            )
        else:
            room.classe = cls
            room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classe_classe_technique'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='classe',
            field=models.OneToOneField(blank=True, help_text='Classe à laquelle cette salle est rattachée (créée automatiquement)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salle_attachee', to='classes.classe'),
        ),
        migrations.RunPython(create_class_rooms, migrations.RunPython.noop),
    ]
