# Generated by Django 6.0.6 on 2026-06-22 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CONFLIT', 'Conflit détecté'), ('MODIFICATION', 'Modification emploi du temps'), ('GENERATION', 'Génération terminée'), ('REMPLACEMENT', 'Remplacement enseignants'), ('INFO', 'Information')], max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('lien', models.CharField(blank=True, help_text='Lien vers la ressource concernée', max_length=300)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
