# Generated by Django 6.0.6 on 2026-06-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContrainteSpecifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrainte', models.CharField(choices=[('INDISP_CLASSE', 'Indisponibilité classe'), ('INDISP_NIVEAU', 'Indisponibilité niveau'), ('INTERDICT_DERN_HEURE', 'Matière interdite en dernière heure'), ('MAT_APMIDI_ONLY', "Matière uniquement l'après-midi"), ('MAT_MATIN_ONLY', 'Matière uniquement le matin'), ('MAX_HEURES_CONSEC', 'Max heures consécutives par matière'), ('SPORT_APMIDI', "Sport uniquement l'après-midi"), ('PAS_COURS_APRES', 'Pas de cours après une heure donnée')], max_length=30)),
                ('jour_semaine', models.IntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi')], null=True)),
                ('heure_limite', models.TimeField(blank=True, help_text='Heure limite pour PAS_COURS_APRES', null=True)),
                ('valeur', models.FloatField(blank=True, help_text='Valeur numérique (ex: max heures consécutives)', null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contraintes', to='classes.classe')),
            ],
            options={
                'verbose_name': 'Contrainte spécifique',
                'verbose_name_plural': 'Contraintes spécifiques',
            },
        ),
    ]
