# Generated by Django 5.1.6 on 2026-07-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0003_alter_contraintespecifique_type_contrainte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraintespecifique',
            name='type_contrainte',
            field=models.CharField(choices=[('INDISP_CLASSE', 'Indisponibilité classe'), ('INDISP_NIVEAU', 'Indisponibilité niveau'), ('INTERDICT_DERN_HEURE', 'Matière interdite en dernière heure'), ('MAT_APMIDI_ONLY', "Matière uniquement l'après-midi"), ('MAT_MATIN_ONLY', 'Matière uniquement le matin'), ('MAX_HEURES_CONSEC', 'Max heures consécutives par matière'), ('PAS_COURS_APRES', 'Pas de cours après une heure donnée'), ('FIN_AVANCEE', 'Fin des cours avancée (ex: vendredi 17h)'), ('HEURES_MIN_JOUR', 'Heures minimum par jour')], max_length=30),
        ),
    ]
