# Generated by Django 5.1.6 on 2026-07-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0005_alter_contraintespecifique_type_contrainte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraintespecifique',
            name='type_contrainte',
            field=models.CharField(choices=[('INDISP_NIVEAU', 'Indisponibilité niveau'), ('MAT_PERIODE', 'Matière en période spécifique (0=matin, 1=après-midi)'), ('MAX_HEURES_CONSEC', 'Max heures consécutives par matière'), ('FIN_AVANCEE', 'Fin des cours avancée (ex: vendredi 17h)'), ('HEURES_MIN_JOUR', 'Heures minimum par jour')], max_length=30),
        ),
    ]
