# Generated by Django 5.1.6 on 2026-07-29 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0006_alter_contraintespecifique_type_contrainte'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraintespecifique',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contraintes', to='rooms.salle'),
        ),
        migrations.AlterField(
            model_name='contraintespecifique',
            name='heure_limite',
            field=models.TimeField(blank=True, help_text='Heure limite pour les indisponibilités', null=True),
        ),
        migrations.AlterField(
            model_name='contraintespecifique',
            name='type_contrainte',
            field=models.CharField(choices=[('INDISP_NIVEAU', 'Indisponibilité niveau'), ('INDISP_SALLE', 'Indisponibilité salle'), ('MAT_PERIODE', 'Matière en période spécifique (0=matin, 1=après-midi)'), ('MAX_HEURES_CONSEC', 'Max heures consécutives par matière'), ('FIN_AVANCEE', 'Fin des cours avancée (ex: vendredi 17h)'), ('HEURES_MIN_JOUR', 'Heures minimum par jour')], max_length=30),
        ),
    ]
