# Generated by Django 6.0.6 on 2026-06-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Remplacement',
                'verbose_name_plural': 'Remplacements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=False)),
                ('score_qualite', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Version d'emploi du temps",
                'verbose_name_plural': "Versions d'emplois du temps",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('est_verrouille', models.BooleanField(default=False, help_text='Créneau verrouillé manuellement')),
                ('est_demi_groupe', models.BooleanField(default=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='classes.classe')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
    ]
