# Generated by Django 6.0.6 on 2026-06-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('schedules', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='teachers.enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='subjects.matiere'),
        ),
        migrations.AddField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='rooms.salle'),
        ),
        migrations.AddField(
            model_name='cours',
            name='salle_secondaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_secondaire', to='rooms.salle'),
        ),
        migrations.AddField(
            model_name='remplacement',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacements', to='schedules.cours'),
        ),
        migrations.AddField(
            model_name='remplacement',
            name='enseignant_remplacant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacements', to='teachers.enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='schedules.scheduleversion'),
        ),
    ]
