# Generated by Django 6.0.6 on 2026-06-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('heures_par_semaine', models.FloatField()),
                ('coefficient', models.FloatField(default=1.0)),
                ('type', models.CharField(choices=[('GENERAL', 'Général'), ('TECHNIQUE', 'Technique'), ('LABORATOIRE', 'Laboratoire'), ('ATELIER', 'Atelier pratique')], default='GENERAL', max_length=20)),
                ('necessite_salle_informatique', models.BooleanField(default=False)),
                ('necessite_laboratoire', models.BooleanField(default=False)),
                ('necessite_atelier', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ClasseMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_par_semaine', models.FloatField()),
                ('est_demi_groupe', models.BooleanField(default=False, help_text='TP en demi-groupe')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='classes.classe')),
            ],
            options={
                'verbose_name': 'Matière de classe',
                'verbose_name_plural': 'Matières de classes',
            },
        ),
    ]
