# Generated by Django 6.0.6 on 2026-06-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classematiere',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_enseignees', to='teachers.enseignant'),
        ),
        migrations.AddField(
            model_name='classematiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_associees', to='subjects.matiere'),
        ),
        migrations.AlterUniqueTogether(
            name='classematiere',
            unique_together={('classe', 'matiere')},
        ),
    ]
