# Generated by Django 5.1.6 on 2026-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classematiere',
            name='groupe',
            field=models.IntegerField(blank=True, help_text='Classes avec le même numéro de groupe suivent le cours ensemble', null=True),
        ),
    ]
