# Generated by Django 5.1.6 on 2026-07-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_classematiere_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classematiere',
            name='groupe',
        ),
        migrations.AddField(
            model_name='classematiere',
            name='est_commun',
            field=models.BooleanField(default=False, help_text='Cours commun avec la classe technique associée'),
        ),
    ]
