# Generated by Django 5.1.6 on 2026-07-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='salle_principale',
            field=models.ForeignKey(blank=True, help_text='Salle par défaut de la classe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='rooms.salle'),
        ),
    ]
