# Generated by Django 5.1.6 on 2026-07-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classe_salle_principale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='salle_principale',
        ),
    ]
