# Generated by Django 5.1.6 on 2026-07-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_classe_salle_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='classe_technique',
            field=models.ForeignKey(blank=True, help_text='Classe technique associée pour les cours communs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_generales', to='classes.classe'),
        ),
    ]
